In [81]:
import pandas as pd
import numpy as np


In [82]:
df_train = pd.read_csv("F:\\Contests\\NebulaNet\\nebulanet\\train.csv")
df_test = pd.read_csv("F:\\Contests\\NebulaNet\\nebulanet\\test.csv")

df_test

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             16500          0.013000       0.01400                   11.89   
1              2637          0.000730       0.12700                   17.22   
2              4980          0.357000       1.13000                    4.78   
3             33421     352000.000000      67.00000                   -5.79   
4             11096     112000.000000      12.00000                   -5.91   
5              4287     630000.000000    1315.00000                   -9.20   
6             27739     849420.000000    1252.00000                   -7.59   
7             12010          0.000780       0.00920                   12.13   
8              2700          0.000180       0.13000                   16.05   
9             14520          0.000820       0.00972                   11.92   
10             3600     320000.000000      29.00000                   -6.60   
11            24020          0.001590       0.01270                   10.55   
12             3610     132000.000000    1522.00000                  -10.86   
13            17383     342900.000000      30.00000                   -6.09   
14             3399     117000.000000    1486.00000                  -10.92   
15            24145     382993.000000    1494.00000                   -8.84   
16             2889          0.000352       0.09730                   16.93   
17             3340          0.003800       0.24000                   13.07   
18            14060       1092.000000       5.74500                   -2.04   
19             3225          0.000760       0.12100                   19.63   
20             2861          0.000190       0.08990                   16.71   
21             3441          0.039000       0.35100                   11.18   
22            38940     374830.000000    1356.00000                   -9.93   
23            39000     204000.000000      10.60000                   -4.70   

    Star color Spectral Class  
0   Blue White              B  
1          Red              M  
2    Yellowish              K  
3         Blue              O  
4         Blue              O  
5       Orange              K  
6   Blue-white              B  
7   Blue White              B  
8          Red              M  
9   Blue White              B  
10         Red              M  
11        Blue              B  
12         Red              M  
13        Blue              O  
14         Red              M  
15  Blue-white              B  
16         Red              M  
17         Red              M  
18  Blue-white              A  
19         Red              M  
20         Red              M  
21         Red              M  
22        Blue              O  
23        Blue              O

In [83]:
df_train.dtypes

Temperature (K)             int64
Luminosity(L/Lo)          float64
Radius(R/Ro)              float64
Absolute magnitude(Mv)    float64
Star type                  object
Star color                 object
Spectral Class             object
dtype: object

In [84]:
from sklearn import preprocessing

labelencode = preprocessing.LabelEncoder()
#labeltransform = ColumnTransformer([("labelencode", labelencode, ["Star type"])], remainder= "passthrough")
Star_type_encoded = labelencode.fit_transform(df_train["Star type"])
Star_type_encoded

array([5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5,
       5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2])

In [85]:
df_train["Star type"] = Star_type_encoded
df_train

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0               3068          0.002400        0.1700                   16.12   
1               3042          0.000500        0.1542                   16.60   
2               2600          0.000300        0.1020                   18.70   
3               2800          0.000200        0.1600                   16.65   
4               1939          0.000138        0.1030                   20.06   
..               ...               ...           ...                     ...   
211            21904     748490.000000     1130.0000                   -7.67   
212            30839     834042.000000     1194.0000                  -10.63   
213             8829     537493.000000     1423.0000                  -10.73   
214             9235     404940.000000     1112.0000                  -11.23   
215            37882     294903.000000     1783.0000                   -7.80   

     Star type  Star color Spectral Class  
0            5         Red              M  
1            5         Red              M  
2            5         Red              M  
3            5         Red              M  
4            5         Red              M  
..         ...         ...            ...  
211          2  Blue-white              B  
212          2        Blue              O  
213          2       White              A  
214          2       White              A  
215          2        Blue              O  

[216 rows x 7 columns]

In [86]:
df_test["Star type"] = 0
df_test

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             16500          0.013000       0.01400                   11.89   
1              2637          0.000730       0.12700                   17.22   
2              4980          0.357000       1.13000                    4.78   
3             33421     352000.000000      67.00000                   -5.79   
4             11096     112000.000000      12.00000                   -5.91   
5              4287     630000.000000    1315.00000                   -9.20   
6             27739     849420.000000    1252.00000                   -7.59   
7             12010          0.000780       0.00920                   12.13   
8              2700          0.000180       0.13000                   16.05   
9             14520          0.000820       0.00972                   11.92   
10             3600     320000.000000      29.00000                   -6.60   
11            24020          0.001590       0.01270                   10.55   
12             3610     132000.000000    1522.00000                  -10.86   
13            17383     342900.000000      30.00000                   -6.09   
14             3399     117000.000000    1486.00000                  -10.92   
15            24145     382993.000000    1494.00000                   -8.84   
16             2889          0.000352       0.09730                   16.93   
17             3340          0.003800       0.24000                   13.07   
18            14060       1092.000000       5.74500                   -2.04   
19             3225          0.000760       0.12100                   19.63   
20             2861          0.000190       0.08990                   16.71   
21             3441          0.039000       0.35100                   11.18   
22            38940     374830.000000    1356.00000                   -9.93   
23            39000     204000.000000      10.60000                   -4.70   

    Star color Spectral Class  Star type  
0   Blue White              B          0  
1          Red              M          0  
2    Yellowish              K          0  
3         Blue              O          0  
4         Blue              O          0  
5       Orange              K          0  
6   Blue-white              B          0  
7   Blue White              B          0  
8          Red              M          0  
9   Blue White              B          0  
10         Red              M          0  
11        Blue              B          0  
12         Red              M          0  
13        Blue              O          0  
14         Red              M          0  
15  Blue-white              B          0  
16         Red              M          0  
17         Red              M          0  
18  Blue-white              A          0  
19         Red              M          0  
20         Red              M          0  
21         Red              M          0  
22        Blue              O          0  
23        Blue              O          0

In [87]:
df = pd.concat([df_train, df_test])
df

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0              3068          0.002400        0.1700                   16.12   
1              3042          0.000500        0.1542                   16.60   
2              2600          0.000300        0.1020                   18.70   
3              2800          0.000200        0.1600                   16.65   
4              1939          0.000138        0.1030                   20.06   
..              ...               ...           ...                     ...   
19             3225          0.000760        0.1210                   19.63   
20             2861          0.000190        0.0899                   16.71   
21             3441          0.039000        0.3510                   11.18   
22            38940     374830.000000     1356.0000                   -9.93   
23            39000     204000.000000       10.6000                   -4.70   

    Star type Star color Spectral Class  
0           5        Red              M  
1           5        Red              M  
2           5        Red              M  
3           5        Red              M  
4           5        Red              M  
..        ...        ...            ...  
19          0        Red              M  
20          0        Red              M  
21          0        Red              M  
22          0       Blue              O  
23          0       Blue              O  

[240 rows x 7 columns]

In [88]:
x = df.drop(columns="Star type", axis = 1)

In [89]:
from sklearn.compose import ColumnTransformer

cf = ["Spectral Class", "Star color"]
encode = preprocessing.OneHotEncoder(sparse_output= False)

transform = ColumnTransformer([("encode", encode, cf)], remainder= "passthrough")
transformed_x = transform.fit_transform(x)
#transformed_x_test = transform.fit_transform(df_test)
#transformed_x


In [90]:
max_abs_scale = preprocessing.MaxAbsScaler()
x_train_abs_scale= max_abs_scale.fit_transform(transformed_x)
#x_test_abs_scale= max_abs_scale.fit_transform(transformed_x_test)
#x_train_abs_scale

In [91]:
x1 = pd.DataFrame(x_train_abs_scale)
x_train = x1[:-24]
x_test = x1[-24:]
y_train = df["Star type"][:-24]
#x_train


In [92]:
from sklearn.ensemble import RandomForestClassifier
#from sklearn.model_selection import train_test_split
np.random.seed(42)

#x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size= 0.2)

model = RandomForestClassifier()
model.fit(x_train, y_train)
y_test = model.predict(x_test)
y_test



array([4, 5, 0, 1, 1, 2, 2, 4, 5, 4, 1, 4, 2, 1, 2, 2, 5, 3, 0, 5, 5, 3,
       2, 0], dtype=int64)

In [121]:
y_label_pred= labelencode.inverse_transform(y_test)



In [122]:
ID = np.arange(1, 25, 1)
ID

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [126]:
solution = pd.DataFrame([ID, y_label_pred]).T
solution.rename(columns= {0: "ID", 1: "Star type"}, inplace=True)
solution

ID             Star type
0    1          Pearl Dwarfs
1    2          Umber Dwarfs
2    3    Aurelian Mainstays
3    4  Celestial Sovereigns
4    5  Celestial Sovereigns
5    6      Cosmic Behemoths
6    7      Cosmic Behemoths
7    8          Pearl Dwarfs
8    9          Umber Dwarfs
9   10          Pearl Dwarfs
10  11  Celestial Sovereigns
11  12          Pearl Dwarfs
12  13      Cosmic Behemoths
13  14  Celestial Sovereigns
14  15      Cosmic Behemoths
15  16      Cosmic Behemoths
16  17          Umber Dwarfs
17  18        Crimson Dwarfs
18  19    Aurelian Mainstays
19  20          Umber Dwarfs
20  21          Umber Dwarfs
21  22        Crimson Dwarfs
22  23      Cosmic Behemoths
23  24    Aurelian Mainstays

In [129]:
solution.to_csv(r"F:\Contests\NebulaNet\nebulanet\Solution.csv", index= False)